# gui/reports_tab.py
import customtkinter as ctk
from tkinter import filedialog, messagebox
import json
import time
import os

class ReportsTab:
    def __init__(self, tab, app):
        self.app = app
        self.create_widgets(tab)
        
    def create_widgets(self, tab):
        tab.grid_columnconfigure(0, weight=1)
        tab.grid_rowconfigure(1, weight=1)
        
        header_frame = ctk.CTkFrame(tab, corner_radius=10, fg_color="#1a1a2e")
        header_frame.grid(row=0, column=0, padx=10, pady=10, sticky="ew")
        header_frame.grid_columnconfigure(1, weight=1)
        
        ctk.CTkLabel(header_frame, text="📊 Security Reports", 
                    font=ctk.CTkFont(size=16, weight="bold"), text_color="#00ff41").grid(row=0, column=0, padx=10)
        
        btn_frame = ctk.CTkFrame(header_frame, fg_color="transparent")
        btn_frame.grid(row=0, column=1, padx=10)
        
        ctk.CTkButton(btn_frame, text="📊 Generate", command=self.generate_report,
                     fg_color="#2ecc71", hover_color="#27ae60", height=30, width=120).pack(side=ctk.LEFT, padx=5)
        
        ctk.CTkButton(btn_frame, text="📄 HTML", command=self.export_html,
                     fg_color="#9b59b6", hover_color="#8e44ad", height=30, width=100).pack(side=ctk.LEFT, padx=5)
        
        ctk.CTkButton(btn_frame, text="📄 JSON", command=self.export_json,
                     fg_color="#3498db", hover_color="#2980b9", height=30, width=100).pack(side=ctk.LEFT, padx=5)
        
        self.log = ctk.CTkTextbox(tab, wrap="word", state="disabled", font=ctk.CTkFont(size=11), fg_color="#0a0a1a")
        self.log.grid(row=1, column=0, padx=10, pady=10, sticky="nsew")
        
        btn_frame2 = ctk.CTkFrame(tab, fg_color="transparent")
        btn_frame2.grid(row=2, column=0, padx=10, pady=10)
        
        ctk.CTkButton(btn_frame2, text="💾 Save", command=self.save_report,
                     fg_color="#3498db", hover_color="#2980b9", height=30, width=100).pack(side=ctk.LEFT, padx=5)
        ctk.CTkButton(btn_frame2, text="🗑️ Clear", command=self.clear_log,
                     fg_color="#95a5a6", hover_color="#7f8c8d", height=30, width=80).pack(side=ctk.LEFT, padx=5)
    
    def log_to_widget(self, msg):
        self.log.configure(state="normal")
        self.log.insert(ctk.END, msg + "\n")
        self.log.see(ctk.END)
        self.log.configure(state="disabled")
    
    def clear_log(self):
        self.log.configure(state="normal")
        self.log.delete("1.0", ctk.END)
        self.log.configure(state="disabled")
    
    def save_report(self):
        content = self.log.get("1.0", ctk.END)
        filename = f"report_{int(time.time())}.txt"
        with open(filename, "w") as f:
            f.write(content)
        messagebox.showinfo("Saved", f"Report saved to {filename}")
    
    def generate_report(self):
        self.clear_log()
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"""
╔═══════════════════════════════════════════════════════════════════╗
║             BLACKCODE ULTIMATE v8.0 - SECURITY REPORT           ║
╠═══════════════════════════════════════════════════════════════════╣
║ Generated: {timestamp}
╠═══════════════════════════════════════════════════════════════════╣
║ Total Vulnerabilities: {len(self.app.vulnerabilities)}
║ Proxy: {'Enabled' if self.app.proxy_config.get('enabled') else 'Disabled'}
╠═══════════════════════════════════════════════════════════════════╣
║ VULNERABILITIES
╠═══════════════════════════════════════════════════════════════════╣
"""
        if self.app.vulnerabilities:
            for i, vuln in enumerate(self.app.vulnerabilities, 1):
                report += f"""
[{i}] {vuln['title']}
    Severity: {vuln['severity']}
    Time: {vuln['timestamp']}
    {vuln['description']}
    {'-' * 60}
"""
        else:
            report += "    ✅ No vulnerabilities found.\n"
        
        report += f"""
╠═══════════════════════════════════════════════════════════════════╣
║ RECOMMENDATIONS
╠═══════════════════════════════════════════════════════════════════╣
║ 1. Regular updates and patches
║ 2. Use strong passwords (16+ chars)
║ 3. Enable 2FA/MFA
║ 4. Regular backups (3-2-1)
║ 5. Monitor logs for suspicious activity
╠═══════════════════════════════════════════════════════════════════╣
║ Generated by BlackCode Ultimate v8.0
╚═══════════════════════════════════════════════════════════════════╝
"""
        self.log_to_widget(report)
    
    def export_html(self):
        content = self.log.get("1.0", ctk.END)
        if not content.strip():
            messagebox.showerror("Error", "Generate report first")
            return
        
        filename = filedialog.asksaveasfilename(defaultextension=".html", filetypes=[("HTML files", "*.html")])
        if not filename:
            return
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>BlackCode Security Report</title>
    <style>
        body {{ font-family: monospace; background: #0a0a1a; color: #00ff41; padding: 20px; }}
        h1 {{ color: #00ff41; border-bottom: 2px solid #00ff41; }}
        .vuln {{ background: #1a1a2e; padding: 10px; margin: 10px 0; border-left: 3px solid #00ff41; }}
        .critical {{ border-color: #ff0000; }}
        .high {{ border-color: #ff6600; }}
        .medium {{ border-color: #ffaa00; }}
        .low {{ border-color: #00ff41; }}
        .footer {{ text-align: center; margin-top: 30px; color: #666688; }}
    </style>
</head>
<body>
    <h1>🛡️ BlackCode Ultimate - Security Report</h1>
    <p>Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}</p>
    <h2>Vulnerabilities: {len(self.app.vulnerabilities)}</h2>
"""
        if self.app.vulnerabilities:
            for vuln in self.app.vulnerabilities:
                severity_class = vuln['severity'].lower()
                html += f"""
    <div class="vuln {severity_class}">
        <b>{vuln['severity']}</b> - {vuln['title']}<br>
        {vuln['description'].replace('\n', '<br>')}
    </div>
"""
        else:
            html += "<p>✅ No vulnerabilities found.</p>"
        
        html += f'<div class="footer">Generated by BlackCode Ultimate v8.0</div></body></html>'
        
        with open(filename, "w") as f:
            f.write(html)
        messagebox.showinfo("Exported", f"HTML report saved to {filename}")
    
    def export_json(self):
        if not self.app.vulnerabilities:
            messagebox.showerror("Error", "No vulnerabilities to export")
            return
        
        filename = filedialog.asksaveasfilename(defaultextension=".json", filetypes=[("JSON files", "*.json")])
        if not filename:
            return
        
        data = {
            'generated': time.strftime("%Y-%m-%d %H:%M:%S"),
            'total_vulnerabilities': len(self.app.vulnerabilities),
            'vulnerabilities': self.app.vulnerabilities
        }
        with open(filename, "w") as f:
            json.dump(data, f, indent=2)
        messagebox.showinfo("Exported", f"JSON report saved to {filename}")
